# Generated by Django 6.0 on 2026-05-24 22:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_analise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContatoWhatsapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Telefone deve conter apenas dígitos, no formato E.164 sem '+' (ex: 5511987654321).", regex='^\\d{12,15}$')], verbose_name='Telefone (E.164 sem +)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Contato WhatsApp',
                'verbose_name_plural': 'Contatos WhatsApp',
                'ordering': ['nome'],
            },
        ),
    ]
