# Generated by Django 6.0 on 2026-05-25 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_analise', '0002_contatowhatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_envio_diario', models.TimeField(blank=True, help_text='Horário em que o relatório diário deve ser enviado. Sem função até o cron estar ativo.', null=True, verbose_name='Horário do envio diário (BRT)')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Configuração de Relatório',
                'verbose_name_plural': 'Configurações de Relatório',
            },
        ),
    ]
