# Generated by Django 6.0 on 2026-02-11 06:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=200, verbose_name='Ação')),
                ('detalhes', models.TextField(blank=True, null=True, verbose_name='Detalhes')),
                ('data_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do Registro')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Log do Supervisor',
                'verbose_name_plural': 'Logs do Supervisor',
                'ordering': ['-data_registro'],
            },
        ),
    ]
