# Generated by Django 6.0 on 2026-02-11 06:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BriefingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Briefing')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('data_sessao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Sessão')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Sessão de Briefing',
                'verbose_name_plural': 'Sessões de Briefing',
                'ordering': ['-data_sessao'],
            },
        ),
    ]
