# Generated by Django 6.0 on 2026-02-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala_briefing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='briefingsession',
            options={'ordering': ['-data', '-horario'], 'verbose_name': 'Sessão de Briefing', 'verbose_name_plural': 'Sessões de Briefing'},
        ),
        migrations.RemoveField(
            model_name='briefingsession',
            name='data_sessao',
        ),
        migrations.RemoveField(
            model_name='briefingsession',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='briefingsession',
            name='titulo',
        ),
        migrations.AddField(
            model_name='briefingsession',
            name='cliente_final',
            field=models.CharField(default='', max_length=100, verbose_name='Cliente Final'),
        ),
        migrations.AddField(
            model_name='briefingsession',
            name='companhia_aerea',
            field=models.CharField(default='', max_length=100, verbose_name='Companhia Aérea'),
        ),
        migrations.AddField(
            model_name='briefingsession',
            name='data',
            field=models.DateField(null=True, verbose_name='Data'),
        ),
        migrations.AddField(
            model_name='briefingsession',
            name='horario',
            field=models.TimeField(null=True, verbose_name='Horário'),
        ),
        migrations.AddField(
            model_name='briefingsession',
            name='numero_voo',
            field=models.IntegerField(default=0, verbose_name='Número do Voo'),
        ),
        migrations.AddField(
            model_name='briefingsession',
            name='servico',
            field=models.CharField(default='', max_length=200, verbose_name='Serviço'),
        ),
        migrations.AddField(
            model_name='briefingsession',
            name='solicitante',
            field=models.CharField(default='', max_length=100, verbose_name='Solicitante'),
        ),
        migrations.AddField(
            model_name='briefingsession',
            name='unidade_maritima',
            field=models.CharField(default='', max_length=100, verbose_name='Unidade Marítima'),
        ),
    ]
