# Generated by Django 6.0 on 2026-02-17 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala_briefing', '0002_alter_briefingsession_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='briefingsession',
            name='prefixo_aeronave',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Prefixo da Aeronave'),
        ),
    ]
