# Generated by Django 6.0 on 2025-12-14 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desembarque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=20, verbose_name='Nº do Voo')),
                ('aeronave', models.CharField(max_length=10, verbose_name='Aeronave')),
                ('operadora', models.CharField(max_length=100, verbose_name='Operador Aéreo')),
                ('arrival_date', models.DateField(verbose_name='Data de Chegada')),
                ('arrival_time', models.TimeField(verbose_name='Hora de Chegada')),
                ('origin', models.CharField(max_length=100, verbose_name='Origem/Plataforma')),
                ('cliente_final', models.CharField(choices=[('PRIO', 'PRIO'), ('PETROBRAS', 'PETROBRAS'), ('SPOT', 'SPOT')], max_length=50, verbose_name='Cliente Final')),
                ('passengers_disembarked', models.IntegerField(default=0, verbose_name='Passageiros Desembarcados')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Registro de Desembarque',
                'verbose_name_plural': 'Registros de Desembarque',
            },
        ),
        migrations.CreateModel(
            name='Embarque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=20, verbose_name='Nº do Voo')),
                ('aeronave', models.CharField(max_length=10, verbose_name='Aeronave')),
                ('operadora', models.CharField(max_length=100, verbose_name='Operador Aéreo')),
                ('departure_date', models.DateField(verbose_name='Data de Embarque')),
                ('departure_time', models.TimeField(verbose_name='Hora do Embarque')),
                ('platform', models.CharField(max_length=50, verbose_name='Plataforma')),
                ('icao', models.CharField(max_length=10, verbose_name='ICAO')),
                ('cliente_final', models.CharField(choices=[('PRIO', 'PRIO'), ('PETROBRAS', 'PETROBRAS'), ('SPOT', 'SPOT')], max_length=50, verbose_name='Cliente Final')),
                ('passengers_boarded', models.IntegerField(default=0, verbose_name='Passageiros Embarcados')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Registro de Embarque',
                'verbose_name_plural': 'Registros de Embarque',
            },
        ),
    ]
