# Generated by Django 6.0 on 2026-02-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacao_voo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='embarque',
            name='passageiros_catraca1',
            field=models.IntegerField(default=0, verbose_name='Passageiros Catraca 1'),
        ),
        migrations.AddField(
            model_name='embarque',
            name='passageiros_catraca2',
            field=models.IntegerField(default=0, verbose_name='Passageiros Catraca 2'),
        ),
        migrations.AddField(
            model_name='embarque',
            name='catraca1_salvo',
            field=models.BooleanField(default=False, verbose_name='Catraca 1 Salva'),
        ),
        migrations.AddField(
            model_name='embarque',
            name='catraca2_salvo',
            field=models.BooleanField(default=False, verbose_name='Catraca 2 Salva'),
        ),
    ]
