# Generated by Django 6.0 on 2026-03-03 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacao_voo', '0002_add_catraca_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desembarque',
            name='cliente_final',
            field=models.CharField(max_length=50, verbose_name='Cliente Final'),
        ),
        migrations.AlterField(
            model_name='embarque',
            name='cliente_final',
            field=models.CharField(max_length=50, verbose_name='Cliente Final'),
        ),
    ]
