# Generated by Django 6.0 on 2026-03-23 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacao_voo', '0003_alter_desembarque_cliente_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='desembarque',
            name='icao',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='ICAO'),
        ),
    ]
