# Generated by Django 6.0 on 2026-02-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrotransporte',
            options={'ordering': ['-data', '-horario'], 'verbose_name': 'Registro de Transporte', 'verbose_name_plural': 'Registros de Transporte'},
        ),
        migrations.RemoveField(
            model_name='registrotransporte',
            name='data_transporte',
        ),
        migrations.RemoveField(
            model_name='registrotransporte',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='registrotransporte',
            name='destino',
        ),
        migrations.RemoveField(
            model_name='registrotransporte',
            name='origem',
        ),
        migrations.AddField(
            model_name='registrotransporte',
            name='cliente_final',
            field=models.CharField(default='', max_length=100, verbose_name='Cliente Final'),
        ),
        migrations.AddField(
            model_name='registrotransporte',
            name='data',
            field=models.DateField(null=True, verbose_name='Data'),
        ),
        migrations.AddField(
            model_name='registrotransporte',
            name='empresa_solicitante',
            field=models.CharField(default='', max_length=100, verbose_name='Empresa que Solicita'),
        ),
        migrations.AddField(
            model_name='registrotransporte',
            name='horario',
            field=models.TimeField(null=True, verbose_name='Horário'),
        ),
        migrations.AddField(
            model_name='registrotransporte',
            name='numero_voo',
            field=models.IntegerField(default=0, verbose_name='Número do Voo'),
        ),
        migrations.AddField(
            model_name='registrotransporte',
            name='prefixo_aeronave',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Prefixo da Aeronave'),
        ),
        migrations.AddField(
            model_name='registrotransporte',
            name='prefixo_manual',
            field=models.CharField(blank=True, default='', help_text='Preencher somente se o campo Prefixo da Aeronave não for informado', max_length=50, verbose_name='Prefixo Manual'),
        ),
        migrations.AddField(
            model_name='registrotransporte',
            name='servico',
            field=models.CharField(default='', max_length=200, verbose_name='Serviço'),
        ),
    ]
