# Generated by Django 6.0 on 2025-12-14 22:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catraca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Catraca 1 - Portão A', max_length=50)),
                ('identificador', models.CharField(max_length=50, unique=True, verbose_name='ID do Dispositivo')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('tipo', models.CharField(choices=[('EMBARQUE', 'Embarque (Soma no Voo de Saída)'), ('DESEMBARQUE', 'Desembarque (Soma no Voo de Chegada)')], max_length=20, verbose_name='Tipo de Operação')),
                ('push_ativo', models.BooleanField(default=False, verbose_name='PUSH Ativo?')),
            ],
        ),
        migrations.CreateModel(
            name='EventoCatraca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('sentido', models.CharField(blank=True, max_length=20, null=True)),
                ('raw_data', models.TextField(blank=True, null=True, verbose_name='Dados Brutos')),
                ('catraca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='controle_acesso.catraca')),
            ],
            options={
                'verbose_name': 'Evento de Giro',
                'verbose_name_plural': 'Eventos de Giro',
                'ordering': ['-timestamp'],
            },
        ),
    ]
