# Generated by Django 6.0 on 2025-12-17 04:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_acesso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catraca',
            name='inicio_contagem',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Início da Contagem Atual'),
        ),
    ]
