# Generated by Django 6.0 on 2026-02-17 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_acesso', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='catraca',
            name='last_command_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último Comando PUSH'),
        ),
        migrations.AddField(
            model_name='catraca',
            name='last_event_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último Evento de Giro'),
        ),
    ]
