# Generated by Django 6.0 on 2026-02-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_acesso', '0004_catraca_last_command_time_catraca_last_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='catraca',
            name='hardware_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ID Hardware ControlID'),
        ),
    ]
