# Generated by Django 6.0 on 2026-02-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_acesso', '0005_catraca_hardware_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='catraca',
            name='sentido_liberacao',
            field=models.CharField(choices=[('anticlockwise', 'Anti-Horário (Padrão Embarque)'), ('clockwise', 'Horário')], default='anticlockwise', max_length=20, verbose_name='Sentido de Liberação'),
        ),
    ]
